import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "../../component/Home/Navbar/ResponsiveNav";
import Footer from "../../component/Home/Footer/Footer";
import ScrollToTop from "../../component/Helper/ScrollToTop";
import ParticlesHero from "../../component/Home/Hero/ParticleBackground";

const font = Inter({ 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Harry Chandra Tsjan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased bg-[#0d0d1f]`}>
        <ParticlesHero />
        <div className="relative z-10">
          <ResponsiveNav />
          {children}
          <Footer />
          <ScrollToTop />
        </div>
      </body>
    </html>
  );
}
