"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _visits_dashboard from './visits-dashboard.bones.json'

configureBoneyard({"color":"#1c1c1c","darkColor":"#1c1c1c","animate":"shimmer","shimmerColor":"#242424","darkShimmerColor":"#242424","speed":"2.4s"})

registerBones({
  "visits-dashboard": _visits_dashboard,
})
